default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
  - post-checkout
  - post-merge

default_stages:
  - pre-commit

exclude: ^CHANGELOG\.md$

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: "tests/data/.+"
      - id: check-yaml
        exclude: ^(helm/|mkdocs\.yml)
      - id: check-added-large-files
      - id: debug-statements
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/pdm-project/pdm
    rev: 2.19.3
    hooks:
      - id: pdm-lock-check

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        additional_dependencies:
          - emotional

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-github-workflows
      - id: check-dependabot

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        exclude: docs/.*\.pyi?$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
      args: ["--write-changes"]
      exclude: ^pdm\.lock$

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
    - id: markdownlint-cli2
      args: ["--fix"]
